### ISSUE TITLE
range problem when implement onSelect with setState

### ISSUE THREAD

**Issue by luigimassa** [clauderic/react-infinite-calendar#112]
Hi, 
I implemented an handler in component
In the handler of my component, I change the state. But then range it's not more disponible
**component**
 ```javascript
<InfiniteCalendar
      height={300}
      selected={today}
      disabledDays={[0, 6]}
      minDate={lastWeek}
      Component={withRange(Calendar)}
      locale={{
        blank: 'Seleziona una data...',
        locale: require('date-fns/locale/it'),
        headerFormat: 'ddd, MMM D',
        todayLabel: {
          long: 'Oggi',
        },
        weekdays: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
        weekStartsOn: 1,
      }}
      displayOptions={{
        layout: 'landscape',
        showOverlay: false,
        shouldHeaderAnimate: false,
        showHeader: false
      }}
      onSelect={this.baseDataCalendar.bind(this)}      <-------
      />
```
**handler**
```javascript
....
baseDataCalendar(dateObject){
  this.setState({
      calendar: dateObject
    })
}
```

**Comment by gaultier** [comment]
I think I have the same problem.

**Comment by clauderic** [comment]
Two things:

First, since `withRange` is a Higher-order component, you should not use it directly in your render method. Instead, store the enhanced component in a variable outside of your component. See https://facebook.github.io/react/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method for more details. This might explain the odd behavior you're seeing.

The other thing I can notice from the excerpt of code you've provided @luigimassa is that while you are storing the selected date in your state, it looks like you're only passing `selected={today}` to the calendar.

**Comment by luigimassa** [comment]
Thank you :+1:

**Comment by luigimassa** [comment]
Hi, 
I tried your suggestions but there the problem remains:
```
                  <InfiniteCalendar
                        Component={range}
                        selected={{
                           start: new Date(2017, 5, 24),
                           end: new Date(2017, 6, 8)
                        }}
                        onSelect={function (data) {
                            console.log(data.start, data.end, data.eventType)
                        }}/>
```
The console log don't display any range...

**Comment by mohitsud** [comment]
in your onSelect, before updating state, be sure to  check the eventType
`onSelect(data) {
  if(data.eventType === 3){
     //update state
  }
}`
