### ISSUE TITLE
Calendar jumps when using redux to manage selected dates

### ISSUE THREAD

**Issue by davidfloegel** [clauderic/react-infinite-calendar#132]
Hi there,

great calendar!

I have an issue with using it with redux-form however.
I'm building a create-event form and store selected dates in an array.

So when clicking a date I trigger this:
```javascript
onChange={d => change('dates', d)}
```

Everything works but the calendar always jumps to the position of the current date! I'm assuming it has something to do with the `selected` array being changed?

Thanks!

David

**Comment by clauderic** [comment]
Could you create a reproduction of this issue in [JSFiddle](https://jsfiddle.net/clauderic/4rhn03do/) or [WebpackBin](https://www.webpackbin.com)? 

As a rule of thumb, you should always provide enough code for the issue to be replicated when you open issues in open source projects. There's really no way for me to help you otherwise.
