### ISSUE TITLE
How can I get the date scroll to?

### ISSUE THREAD

**Issue by shikelong** [clauderic/react-infinite-calendar#38]
Now the onScroll Event can only get some Number. 

Regards.

**Comment by clauderic** [comment]
This isn't something that's currently supported, though feel free to submit a PR. I don't know what your use case is, but if you're only interested in knowing if a user has scrolled past a specific date, then you can calculate the specific offset of that date and compare the scroll offset to that. 

Otherwise you can get a general idea of the current week being scrolled over by calculating the current scrollTop offset divided by rowHeight and calculating the number of weeks elapsed since `minDate`. Something along the lines of:
```js
var currentWeek = minDate.add(Math.round(scrollTop/rowHeight), 'weeks');
```

**Comment by shikelong** [comment]
Thank you.
