### ISSUE TITLE
Can't install calendar

### ISSUE THREAD

**Issue by RepositoryNY** [clauderic/react-infinite-calendar#69]
When I'm executing `npm i react-infinite-calendar --save`, it writes:

```
 +-- UNMET PEER DEPENDENCY react-addons-css-transition-group@^0.14.0 || ^15.0.0
 +-- UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0
 `-- react-infinite-calendar@1.2.2
   +-- classnames@2.2.5
   +-- dom-helpers@2.4.0
   +-- moment-range@2.2.0
   +-- UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0
   `-- react-virtualized@8.11.4
```

The problem with this dependencies, I can't use the calendar without them, installing them separately have no effect at all.
How can I properly install the calendar?

**Comment by traumatic** [comment]
I can confirm that.

**Comment by clauderic** [comment]
Which version of React do you have installed?

**Comment by traumatic** [comment]
15.4.2

**Comment by RepositoryNY** [comment]
15.3.2

**Comment by clauderic** [comment]
Hey guys, sorry for the delay. These issues should all be addressed with the upcoming version 2.0 release, which should be happening within the next couple of days.

If you'd like to test it out ahead of it's release, run `npm install react-infinite-calendar@next`

**Comment by RepositoryNY** [comment]
Still have ` +-- UNMET PEER DEPENDENCY react-addons-css-transition-group@^0.14.0 || ^15.0.0`, with `npm install react-infinite-calendar@next`

**Comment by clauderic** [comment]
That means you probably have a version of `react-addons-css-transition-group` installed locally that's older than 15.4.2.

`react-addons-css-transition-group` is a peerDependency, meaning it's left to the end-user to manage the version they have installed locally. This is done to avoid version conflicts that can arise by having divergent/incompatible versions of `react`, `react-dom` and `react-addons-css-transition-group` installed locally.

The following dependencies must be specified by your project in order to avoid version conflicts: react, react-dom, react-addons-css-transition-group. NPM will not automatically install these for you but it will show you a warning message with instructions on how to install them.
