### ISSUE TITLE
onSelect callback when using withRange() should pass an EventType

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#77]
Currently, when you are selecting a range of dates using the withRange() HOC, the onSelect callback gets called every time the range changes.  When the user clicks the second time to fix the range, the onSelect callback gets called again. There is not currently a way to differentiate between the start click, the end click and all the middle mouse movements.  This is important information that the parent app will need to have. At the minimum, the app needs to know when the user has stopped selecting a range of dates so that it can do whatever expensive processing it needs to do.

I see two ways to do this.

1) Add two additional callbacks `onSelectionStart()` and `onSelectionEnd()` 
2) Add some metadata to the object passed to `onSelect()` to distinguish what type of event it is
```
{
	start: DATE,
	end: DATE,
	selectStart: false,
	isSelecting: true,
	selectEnd: false
}
```

This way, the app can ignore the noise, if it only cares about the final range.

**Comment by clauderic** [comment]
That's a really good point @offsky!

I think the best approach would be to add an `eventType` property that could be one of `EVENT_TYPE.HOVER || EVENT_TYPE.CLICK` so the end-user can decide how to handle that event. 

The default exported [InfiniteCalendar](https://github.com/clauderic/react-infinite-calendar/blob/master/src/index.js#L15) component is uncontrolled (meaning it manages it's own internal state).

I mention this because InfiniteCalendar is simply a thin wrapper around the base `Calendar` component. Behind the scenes, `Calendar`, is a controlled component, meaning it does not have any internal state with regards to the selected date(s), and will always read from whatever selected prop is passed to it.

In practice, this means that if you wanted to disable the hover behavior, you could choose to selectively ignore events of type `EVENT_TYPE.HOVER`, and choose not to update the state of your application.

Happy to accept a PR for this if you want to take a stab at it. If not, I should get around to it fairly soon 👍

**Comment by offsky** [comment]
Yes, I agree with your approach. Its probably faster for you to do this, but once I get up to speed on the new codebase, and get some time, if this isn't done yet, I'll take a crack at it.

**Comment by offsky** [comment]
Ok, this was actually pretty easy.  PR coming tomorrow.

**Comment by offsky** [comment]
Any obvious changes that you want: https://github.com/Toodledo/react-infinite-calendar/commit/0eafb3e89fb78650760c3cd00c5d127044a656a1

**Comment by clauderic** [comment]
Looks great! Only thing I'd change is I'd put the eventTypes within the same file and make sure they're exported (so that end-users can use them for comparisons). Also, I tend to always use all caps for constants (EVENT_TYPES vs eventTypes)

Oh, last nitpick, you could do something like this to add the eventType:
```js
onSelect({
  eventType: EVENT_TYPE.END,
  ...getSortedSelection({
    start: selectionStart,
    end: date
  })
});
```

**Comment by JonesXavi** [comment]
@clauderic 
Hi
It would be great if you could help out with onSelect in RangeSelection. I'm not sure how to use your above suggested way. 
I'm trying to do something like this :
        `<InfiniteCalendar width={400} height={300} Component={withRange(Calendar)}
	selected={{ start: new Date(), end: new Date() }} />`

**Comment by offsky** [comment]
That looks good to me. You're just missing the onSelect prop.
```
<InfiniteCalendar 
  width={400} 
  height={300} 
  Component={withRange(Calendar)} 
  selected={{ start: new Date(), end: new Date() }}
  onSelect={function(data) {
     console.log(data.start, data.end, data.eventType)
  }}
/>
