### ISSUE TITLE
Ability to highlight dates or date ranges

### ISSUE THREAD

**Issue by aidanlister** [clauderic/react-infinite-calendar#99]
I need to highlight a window of opportunity, e.g. you can pick any date, but these two weeks are preferred. For my case is tolerance periods for routine maintenance, but it might be discounted or off season rates, etc.

Is there any way to achieve this currently? If not, would you welcome a PR? If so can you point me in the right direction?

Thanks,

**Comment by clauderic** [comment]
Hey @aidanlister, this isn't something that's built currently, but PRs are certainly welcome if you come up with something that can be useful to others.

As of version `2.0.0`, you can now enhance `react-infinite-calendar` using [recompose](https://github.com/acdlite/recompose). Take a look at the implementation for `withMultipleDates` and `withRange`, they should point you in the right direction to build your own HOC that would add this functionality.

Going to close this issue because this isn't something I plan on working myself, but we can keep chatting here or in a PR.

**Comment by vijayst** [comment]
I wrote [an article how to highlight dates](https://vijayt.com/post/highlighting-dates-react-infinite-calendar/) outside of react-infinite-calendar.
